const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('portfolioApp', {
  load: () => ipcRenderer.invoke('data:load'),
  save: data => ipcRenderer.invoke('data:save', data),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: settings => ipcRenderer.invoke('settings:save', settings),
  notifyAgent: payload => ipcRenderer.invoke('agent:notify', payload),
  testAgentNotification: () => ipcRenderer.invoke('agent:testNotification'),
  refreshMacro: force => ipcRenderer.invoke('macro:refresh', Boolean(force)),
  trendsInterest: payload => ipcRenderer.invoke('trends:interest', payload),
  localAiStatus: () => ipcRenderer.invoke('localAi:status'),
  downloadLocalModel: () => ipcRenderer.invoke('localAi:downloadModel'),
  generateOverview: payload => ipcRenderer.invoke('localAi:generateOverview', payload),
  generateNewsImpact: payload => ipcRenderer.invoke('localAi:generateNewsImpact', payload),
  generateThesis: payload => ipcRenderer.invoke('localAi:generateThesis', payload),
  analyzeEvidence: payload => ipcRenderer.invoke('localAi:analyzeEvidence', payload),
  earningsDocuments: payload => ipcRenderer.invoke('earnings:documents', payload),
  searchTickers: query => ipcRenderer.invoke('market:search', query),
  trendingStocks: () => ipcRenderer.invoke('market:trending'),
  usCommonStockCandidates: () => ipcRenderer.invoke('market:usCommonStockCandidates'),
  usCommonStockUniverse: () => ipcRenderer.invoke('market:usCommonStockUniverse'),
  secAgentEvidence: symbol => ipcRenderer.invoke('market:secAgentEvidence', symbol),
  gdeltAgentEvidence: payload => ipcRenderer.invoke('market:gdeltAgentEvidence', payload),
  openRedditSearch: symbol => ipcRenderer.invoke('reddit:openSearch', symbol),
  redditPosts: symbol => ipcRenderer.invoke('market:redditPosts', symbol),
  youtubeEvidence: payload => ipcRenderer.invoke('market:youtubeEvidence', payload),
  refreshAllMarketData: symbols => ipcRenderer.invoke('market:refreshAll', symbols),
  earningsMarkers: symbol => ipcRenderer.invoke('market:earningsMarkers', symbol),
  refreshChart: payload => ipcRenderer.invoke('market:chart', payload),
  refreshMarketData: payload => ipcRenderer.invoke('market:refresh', payload),
  getShortableShares: payload => ipcRenderer.invoke('shortableShares:get', payload),
  launchIbkrGateway: () => ipcRenderer.invoke('ibkr:launchGateway'),
  onShortableSharesUpdated: callback => ipcRenderer.on('shortable-shares:updated', (_, update) => callback(update)),
  onShortableSharesStatus: callback => ipcRenderer.on('shortable-shares:status', (_, status) => callback(status)),
  snapTradeStatus: () => ipcRenderer.invoke('snaptrade:status'),
  saveSnapTradeConfig: details => ipcRenderer.invoke('snaptrade:saveConfig', details),
  connectSnapTrade: options => ipcRenderer.invoke('snaptrade:connect', options || {}),
  syncSnapTrade: () => ipcRenderer.invoke('snaptrade:sync'),
  manualRefreshSnapTrade: () => ipcRenderer.invoke('snaptrade:manualRefresh'),
  onSnapTradeUpdated: callback => ipcRenderer.on('snaptrade:updated', () => callback()),
  exportBackup: data => ipcRenderer.invoke('backup:export', data),
  importBackup: () => ipcRenderer.invoke('backup:import')
});

